#!/bin/bash

AUDIO_HIGH_SYMBOL=' '
AUDIO_LOW_SYMBOL=' '
AUDIO_MUTED_SYMBOL=' '

VOLUME=$(pacmd list-sinks | grep "volume: front" | grep -o "[0-9]*%" | head -1)
MUTED=$(pacmd list-sinks | grep "muted:")
VOLUME="${VOLUME%?}"

SYMBOL=$AUDIO_HIGH_SYMBOL
[[ $VOLUME -le 50 ]] && SYMBOL=$AUDIO_LOW_SYMBOL
[[ $VOLUME -eq 0 ]] && SYMBOL=$AUDIO_MUTED_SYMBOL

echo "$SYMBOL$VOLUME%"
